# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Cloudevents pydantic
site_description: 'An implementation of the CloudEvents spec using pydantic'
site_author: 'Federico Busetti'
docs_dir: docs/
repo_name: 'febus982/cloudevents-pydantic'
repo_url: 'https://github.com/febus982/cloudevents-pydantic'

plugins:
  - search
  - mike
  - awesome-pages
#  - macros:
#      modules:
#        - mkdocs_macros_adr_summary
#  - gen-files:
#      scripts:
#        - scripts/gen_pages.py  # or any other name or path
#  - mkdocstrings:
#      handlers:
#        python:
#          options:
#            docstring_style: sphinx
#            docstring_section_style: spacy

# Do not use the nav section in this file but reference to the .pages files
# in the docs/ directory and subdirectories (awesome-pages plugin)
# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
#nav:
#  - Home: index.md

theme:
  name: material
  custom_dir: mkdocs-overrides
  features:
    - navigation.expand
    - navigation.top
    - content.code.copy

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to auto mode

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/federico-b-a0b78232
  version:
    provider: mike
    default: stable

markdown_extensions:
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.superfences
